# Generated by Django 6.0.2 on 2026-04-19 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='icon',
        ),
    ]
