# Generated by Django 6.0.2 on 2026-04-20 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('lost', "Yo'qolgan"), ('found', 'Topilgan')], default='lost', max_length=10),
        ),
    ]
