# Generated by Django 6.0.2 on 2026-04-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('found', 'Topildi'), ('success', 'Muvoffaqiyatli')], default='active', max_length=20),
        ),
    ]
