# Generated by Django 6.0.2 on 2026-04-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_item_city_alter_item_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('active', 'Aktiv'), ('found', 'Topildi'), ('success', 'Muvaffaqiyatli')], default='active', max_length=20),
        ),
    ]
